---
# Настройки подключения
mongodb_monitoring_user: "{{ vault_mongodb_monitoring_user }}"
mongodb_admin_user: "{{ vault_mongodb_admin_user }}"
mongodb_monitoring_auth_db: "admin"
mongodb_auth_source: "admin"

# Параметры обновления
mongodb_package_name: "mongodb-org"
mongodb_service_name: "mongod"
upgrade_priority:
  secondary_first: true
  delay_between_nodes: 300

# Параметры Zabbix
zabbix_server: "monitoring.example.com"
zabbix_agent_packages:
  - zabbix-agent2

# Пути для скриптов
mongodb_scripts_dir: "/opt/zabbix/scripts"
mongodb_log_dir: "/var/log/zabbix"

# SystemD настройки
mongodb_systemd_overrides:
  LimitNOFILE: 64000
  LimitNPROC: 64000
