---
# Установка необходимых пакетов
- name: Install required packages (Debian/Ubuntu)
  apt:
    name:
      - jq
      - mongodb-clients
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
  tags:
    - packages
    - bootstrap

- name: Install required packages (RHEL/CentOS)
  yum:
    name:
      - jq
      - mongodb-org-shell
    state: present
  when: ansible_os_family == 'RedHat'
  tags:
    - packages
    - bootstrap

# Создание необходимых директорий
- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: zabbix
    group: zabbix
    mode: "0750"
  loop:
    - "{{ mongodb_monitoring.scripts_dir }}"
    - "{{ mongodb_monitoring.log_dir }}"
    - /etc/zabbix
  tags:
    - setup

# Развертывание скриптов мониторинга
- name: Deploy MongoDB monitoring scripts
  copy:
    src: "files/{{ item }}"
    dest: "{{ mongodb_monitoring.scripts_dir }}/{{ item }}"
    owner: zabbix
    group: zabbix
    mode: "0750"
  loop:
    - mongodb_discovery.sh
    - mongodb_io_wait.sh
    - mongodb_repl_status.sh
    - mongodb_connections.sh
  notify: Restart Zabbix Agent
  tags:
    - scripts

# Развертывание файла аутентификации
- name: Deploy MongoDB credentials file
  template:
    src: templates/mongodb_creds.conf.j2
    dest: "{{ mongodb_monitoring.creds_file }}"
    owner: zabbix
    group: zabbix
    mode: "0600"
  no_log: true
  tags:
    - credentials

# Настройка Zabbix
- name: Configure Zabbix monitoring
  template:
    src: templates/userparameter_mongodb.conf.j2
    dest: /etc/zabbix/zabbix_agentd.d/userparameter_mongodb.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Zabbix Agent
  tags:
    - zabbix

# Проверка работы скриптов
- name: Test MongoDB monitoring scripts
  command: "{{ mongodb_monitoring.scripts_dir }}/{{ item }} --test"
  register: script_test
  changed_when: false
  ignore_errors: yes
  loop:
    - mongodb_discovery.sh
    - mongodb_io_wait.sh
    - mongodb_repl_status.sh
    - mongodb_connections.sh
  tags:
    - validation
